### ISSUE TITLE
Discord: add twitter bot to cadCAD discord

### ISSUE THREAD

**Issue by seichris** [cadCAD-org/Working-Groups#19]
## 📋 Anything to add?

follow @cadcad_org and @cadcad_edu

## 🎉 Subtasks

- [ ] Set up dedicated discord 'twitter activity' channel
- [ ] Set up bot

## 🤼‍♂️ Reviewer

@DrCatman 

## 🔗 Work doc - inspirational links

--

## 🔧 Status

--

## 👷 Skills

--

**Comment by Jeff-Emmett** [comment]
Hey @DrCatman, can you sync with @seichris about progress on this task so far?  I'm not sure if there has been contact with Kay from Giveth yet (@geleroyale), but I can add him to this repo as well if further coordination is required.

**Comment by seichris** [comment]
@DrCatman Let's chat in discord. I am @chriscyphert in the cadCAD chat.

**Comment by DrCatman** [comment]
there is a matrix.org/bridge for twitter. If we're already using matrix to plumb other chats, we can set up a twitter feed with it as well
