### ISSUE TITLE
Legal: research incorporate cadCAD community as nonprofit

### ISSUE THREAD

**Issue by seichris** [cadCAD-org/Working-Groups#23]
## 📋 Anything to add?

research legal structures, determine suitable structures and costs (upfront and maintaince).

## 🎉 Subtasks

- [ ] ...

## 🤼‍♂️ Reviewer, Reported By

..., @zargham

## 🔗 Work doc - inspirational links

--

## 🔧 Status

--

## 👷 Skills

legal, financial and business

**Comment by Jeff-Emmett** [comment]
@DrCatman in convo with Linux foundation, Numfocus, Apache foundation, other legal advice to see about advice for non-profit instantiation w/ governance innovation.
