### ISSUE TITLE
Manage monthly Community Call

### ISSUE THREAD

**Issue by Jeff-Emmett** [cadCAD-org/Working-Groups#28]
📋 Anything to add?
Brief article explaining the structure & processes of cadCAD community, ref: CommunityRule.

🎉 Subtasks
- [ ] Determine & confirm presenter & topic for upcoming call (first Wed of each month)
- [ ] Maintain community call notes: https://docs.google.com/document/d/1ESG9Ty838mdcJ_-SR_43Ke_nAOCAfBbvPq_pxRQfNnY/edit#
- [ ] Posts 1 week & 1 hour in advance on cadCAD Twitter with calendar invite
- [ ] Post in appropriate TG & Discord channels with meeting room link (discord voice channel)
- [ ] Coordinate recording and uploading of call 

🤼‍♂️ Reviewer, Reported By
@Jeff-Emmett

🔗 Work doc - inspirational links
--

**Comment by Jeff-Emmett** [comment]
- March presenter still TBD for Asia/Europe version of the community call.
- Tannr Allard is down for an April presentation of TokenCAD.

**Comment by phacker3** [comment]
**May call:**
- Facilitator: James (also recording meeting)
- Presenter: Peter Hacker (me!) topic: cadCAD boot camp and simple, user-friendly models

(@Jeff-Emmett FYI, testing access!)
