### ISSUE TITLE
cadCAD onboarding and organizing

### ISSUE THREAD

**Issue by iviangita** [cadCAD-org/Working-Groups#30]
📋 Anything to add?

Currently, cadCAD is in a shift from blockscience to the community. To get towards a fully community-owned cadCAD, this needs work on the core dev side, in infrastructure/admin tasks, as well as outreach and education to get more people involved.

🎉 Subtasks

[This sheet lists all tasks.](https://docs.google.com/spreadsheets/d/1CQ8_Iy-j2tw39l6pmSCAf-YFGK4dksigYtauoowSj0o/edit#gid=828917017) The next milestone is the release of the [blockscience labs,](https://blocksciencelabs.com/) a collaborative modelling environment, simplifying the process around getting started with and coding cadCAD.

From those tasks, I started working on:

[X] Read and watch all the stuff on cadCAD
[ ] Outreach/Education: Help with Token Engineering workshop
[X] Infra/Admin: Convert spreadsheet issues to public github issues
[ ] Infra/Admin: Help with bridging chats and Twitter from and to the cadCAD Discord chat #18 #19

🤼‍♂️ Reviewer
@ Jeff-Emmett

🔗 Work doc - inspirational links
We coordinate in the cadCAD channels for [Infra/Admin](https://discord.com/channels/722946313775480845/733036591588835399) and for [Outreach](https://discord.com/channels/722946313775480845/733040735712182324)

Copied from CS repo[ issue 231 ](https://app.zenhub.com/workspaces/commons-stack-workspace-5f1206c0362e7b000fc0161b/issues/commons-stack/iteration0/231)

**Comment by Jeff-Emmett** [comment]
I believe we are all up to date on this issue, unless there is anything outstanding on your end @seichris ?
