### ISSUE TITLE
Robots & Marbles model updates

### ISSUE THREAD

**Issue by Jeff-Emmett** [cadCAD-org/Working-Groups#31]
📋 Anything to add?
Roger has been working on standardizing nomenclature on the R&M tutorial.

🎉 Subtasks

[ ] Have community dev look into variable nomenclature and determine if fit with cadCAD processes.
[ ] PR merge & complete

🤼‍♂️ Reviewer
@tylerdmace @Jeff-Emmett 

🔗 Work doc - inspirational links
https://github.com/cadCAD-org/demos/pull/27

**Comment by rogervs** [comment]
Deleted https://github.com/cadCAD-org/demos/pull/27 as it is too far behind the master branch. It will be quicker for me to submit a pull request on the new directory structure @tylerdmace

**Comment by rogervs** [comment]
Robot and marbles tutorials updated, awaiting feedback:

[Robot and Marbles #1](https://github.com/cadCAD-org/demos/pull/35)

[Robot and Marbles #2](https://github.com/cadCAD-org/demos/pull/36)

[Robot and Marbles #3](https://github.com/cadCAD-org/demos/pull/37)

[Robot and Marbles #4](https://github.com/cadCAD-org/demos/pull/38)

[Robot and Marbles #5](https://github.com/cadCAD-org/demos/pull/39)

[Robot and Marbles #6](https://github.com/cadCAD-org/demos/pull/40)

[Robot and Marbles #7](https://github.com/cadCAD-org/demos/pull/41)

@Jeff-Emmett

**Comment by Jeff-Emmett** [comment]
Thanks for the help @rogervs!!

@tylerdmace will take a look at these and pull in anyone else as required.

**Comment by tylerdmace** [comment]
These have been merged. Closing.
