### ISSUE TITLE
Community call - June 2nd

### ISSUE THREAD

**Issue by phacker3** [cadCAD-org/Working-Groups#35]
📋 Planning and execution tasks for June community call. Relevant links:
- Community call agenda & meeting minutes: https://docs.google.com/document/d/1ESG9Ty838mdcJ_-SR_43Ke_nAOCAfBbvPq_pxRQfNnY/edit?usp=sharing
- Meeting recordings repository: https://www.youtube.com/playlist?list=PLzL4U4Szfai00_segN6mVnIi4inh5IhMb

🎉 Subtasks

[ X ] Schedule on community calendar (June 2nd - Time zones?)
[ X ] Find presenter: Shawn Anderson & Sem re: Bonding Curve Modelling
[ X ] Find facilitator / recorder: **Peter hacker**
[ ] Find note taker: 
[ ] Marketing: Twitter posts: **coordinate w/o June 24th**
[ ] Marketing: Discord channels: **coordinate w/o June 24th**

🤼‍♂️ Reviewer
@phacker3 , @Jeff-Emmett

**Comment by Jeff-Emmett** [comment]
Sounds like Shawn and Sem are down to discuss bonding curve modelling for this upcoming call =)

Community call recordings can be found on the cadCAD youtube playlist:  https://www.youtube.com/playlist?list=PLzL4U4Szfai00_segN6mVnIi4inh5IhMb

There are also recording links in the notes, although they may not be 100% up to date.

**Comment by phacker3** [comment]
Thanks for recruiting Jeff!

Last steps are to have a bit of a marketing push (coordinating in discord #education-outreach channel) and finding a note taker - but worst case I can do that myself too.
