### ISSUE TITLE
Community Call July 7th, 2021

### ISSUE THREAD

**Issue by phacker3** [cadCAD-org/Working-Groups#36]
📋 Planning and execution tasks for June community call.

Relevant links:
- Community call agenda & meeting minutes: https://docs.google.com/document/d/1ESG9Ty838mdcJ_-SR_43Ke_nAOCAfBbvPq_pxRQfNnY/edit?usp=sharing
- Meeting recordings repository: https://www.youtube.com/playlist?list=PLzL4U4Szfai00_segN6mVnIi4inh5IhMb
- Marketing content drafts: https://docs.google.com/document/d/1Jsyzvb8WFNUIexZHh9hIb2tZmPoYK9zAPdEu3gY23-M/edit?usp=sharing
- Marketing content visual templates: https://docs.google.com/presentation/d/1sP8-WGppQGtSeN6Et12xdSqmHtjjahT5L9PqBY1msus/edit?usp=sharing

🎉 Subtasks

[ X ] Schedule on community calendar (July 7th - Asia/Europe time zone; 10am CET)
[ X ] Find presenter: Jamsheed (connected through Jeff/Barlin)
[ X ] Find facilitator / recorder: Peter Hacker
[ X ] Find note taker: Peter Hacker
[ X ] Admin: Update community calendar invite with presenter & agenda
[ X ] Marketing: Twitter post: ~1 week (asap once presenter confirmed)
[ O - skipped too close to first tweet ] Marketing: Twitter post: 1 day
[ X ] Marketing: Discord channels (cadCAD, TEC, any others relevant to topic or presenter): 1 day
[ X - bridged ] Marketing: Telegram channel: 1 day
[ X ] Marketing: Twitter post: 1 hour

[ X ] Follow-up: Discord +1 day
[ X - bridged ] Follow-up: Telegram +1 day
[ X ] Upload recording

🤼‍♂️ Reviewer
@phacker3 , @Jeff-Emmett

**Comment by Jeff-Emmett** [comment]
Awesome stuff Peter, thanks for being on top of this!

Looking forward to checking out the recording.
